trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Post-Build
  jobs:
  - job: BuildJob
    displayName: Build the application
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
      displayName: 'Install dependencies'
    
    - script: |
        mkdir -p build
        cd build
        cmake ..
        make
      displayName: 'Compile and build the project'

    - script: echo "Build completed"
      displayName: 'Post-build notification'